### PR TITLE
cypherQuery: Return DataFrames.DataFrame from MATCH query

### PR DESCRIPTION
**Pull request by StefanHaunsberger**
`cypherQuery` uses the 'transaction/commit' endpoint and does not need a separate transaction anymore as it is a single transaction call.
It allows querying for tabular results and returns a DataFrames.DataFrame object.

### CODE REVIEW

**Comment by StefanHaunsberger** [comment]
@glesica 
I added the parameter `nRowsElTypeCheck` ... do you think it is needed? I just thought if someone retrieves a lot of data then only the first 1000 are enough (default)

**Comment by glesica** [comment]
Hey, sorry I've been slow to look at this, been very busy. I'll do my best to review it this weekend.

**Comment by StefanHaunsberger** [comment]
@glesica 
I also have to increase the version to 0.6.1 for the next package version. I will do so tomorrow and add the changes to the repository.
Have a nice evening.

**Comment by StefanHaunsberger** [comment]
@glesica You think I can merge the pull request and create a new tag for a new version, something like 1.1.0?

**Comment by glesica** [comment]
Yep, looks good, thanks! Sorry for the delay, I've been crazy busy. Glad I gave you merge access :)

--
George Lesica
george@lesica.com

**Pull request merged**
