### PR TITLE
merged both plain REST calls and cypher transactions

### PR DESCRIPTION
**Pull request by somasdhavala**
- updated high-level wrapper functions for basic graph mutations, fixed some depreciated syntac, json parsing errors, added http basic authentication
- merged cypher transactions under the same umbrella
- potentially can write bolt-based drivers

### CODE REVIEW

**Comment by glesica** [comment]
@somasdhavala I don't intend to support the REST endpoints in this library since they aren't very useful in practice. I think you may have been working from an old version of the code, since it already supports basic auth. Please take a look at the latest master.

**Comment by somasdhavala** [comment]
@glesica i did check out the recent master. your transactions were incorporated. it is possible to have same functionality (create node, for eg.) in multiple ways via 1) REST, via 2) transactions and via 3) (future) via Bolt.

**Comment by glesica** [comment]
I guess my point was that I am not going to merge this PR with the REST code included. Also, it seems that you attempted to merge the new stuff back into the old stuff, which won't work (hence the merge conflicts). If you'd like me to consider a particular feature, I'd be happy to accept a PR, but it will need to be a lot cleaner than this, and it can't include anything related to the Neo4j REST API.

**Comment by somasdhavala** [comment]
ok, np. thanks!

**Pull request closed without merging**
