### PR TITLE
fix: Fix deprecations

### PR DESCRIPTION
**Pull request by StefanHaunsberger**
Fixed deprecations by following changes: 
- `immutable` to `struct`
- change of parameter type definitions from `f{T<:type}`  to `f(x::T) where {T<:type}`
- `typealias` with `const` syntax, e.g. `typealias JSONArray Union{Vector,Void}` to `const JSONArray = Union{Vector,Void}`

-> Run `Pkg.test("Neo4j")` with output: All tests passed!

### CODE REVIEW

**Review by glesica — APPROVED** [review]
Looks great, thanks so much! I'd love to get to a point where the unit tests don't require a running Neo4j instance, I need to find some time to make that happen.

**Comment by glesica** [comment]
I think CI would pass if you bumped the Julia version in the Travis config file.

**Comment by StefanHaunsberger** [comment]
Thanks very much!
To which version would you like me to bump the Julia version to?

> I'd love to get to a point where the unit tests don't require a running Neo4j instance

True...In the case of Java stored procedures I wrote for my Neo4j GDB there a kind of micro instance is spinned up in kind of a sandbox which lets you run the tests even if you don't have a running Neo4j instance. But of course, that's Java...different story.

In the next days I'm going to implement the parsing the result of a Cypher query into `DataFrames.DataFrame` objects, if that suits.

**Comment by glesica** [comment]
> To which version would you like me to bump the Julia version to?

Since we're using new syntax here, why don't we go to 0.6.x, until Julia hits 1.0 I don't personally feel a strong need to worry about backward compatibility.

> In the next days I'm going to implement the parsing the result of a Cypher query into `DataFrames.DataFrame` objects, if that suits.

That sounds like a really good idea to me!

**Comment by StefanHaunsberger** [comment]
> Since we're using new syntax here, why don't we go to 0.6.x, until Julia hits 1.0 I don't personally feel a strong need to worry about backward compatibility.

Sounds good to me! As this is my first Julia package contribution, sorry to ask this question, but I was wondering what is the proper way to increase the version? I know in R it is just simply increasing the version number in the description file...but in Julia?

I'd first push/merge the deprecation fix and then the `DataFrames.DataFrame`/`JuliaDB.table` cypher querying.

**Comment by glesica** [comment]
You just have to update the `.travis.yml` file and the `REQUIRE` file. In the former, just replace the list of versions:

```
  - 0.4
  - 0.5
  - nightly
```

with 0.6:

```
  - 0.6
```

In the require file you just have to replace `julia 0.4` with `julia 0.6`.

**Comment by StefanHaunsberger** [comment]
I think I accidentically pushed changes to your github repo :( sorry for that!!
I'm currently having troubles with adding commits to the pull request. I did as they described it on the Julia website but it looks like my locally created branch "fix-deprecations" did not get pushed to my repo?!

**Comment by StefanHaunsberger** [comment]
I've updated the yml and REQUIRE file. The nightly build fails because of some other packages failing to build under Julia v0.7. The 0.6 passes the check in travis.

**Comment by StefanHaunsberger** [comment]
Would you like me to do a Squash Merge before I submit the data-sink parsing implementation?

**Comment by glesica** [comment]
This looks good to me, thanks everyone! I'll just merge as-is, I don't usually worry too much about the commit history.

**Pull request merged**
